### ISSUE TITLE
add animation

### ISSUE THREAD

**Issue by joelmiller** [springer-math/Mathematics-of-Epidemics-on-Networks#16]
create animation.  Main image should be graph changing in time.  On side include plot with S, I, and R with bar showing advance of time.

animate(display_times, t, full_data, SIR=True, pos =None, colorS=X, colorI = Y, colorR=Z)

include optional keywords for nx.draw.

**Comment by joelmiller** [comment]
This is currently in progress.  Want to have the ability to add plots to the time series.

**Comment by joelmiller** [comment]
done with 0.99.1

**Comment by chengjun** [comment]
I would be a great to support interactive visualization:

``
from ipywidgets import interact, fixed
interact(sim.display, time=[0, 10], node_size = 4 )
``
