### ISSUE TITLE
Discrete SIR with variable Tr and B

### ISSUE THREAD

**Issue by debmalya191** [springer-math/Mathematics-of-Epidemics-on-Networks#35]
Hi

@joelmiller  I was trying to implement a SIR model with a variable transmission rate and infection rate with a discrete time . I could only find basic_discrete_SIR which has a transmission rate as 1.  Therefore I was wondering if there is such a function already in the package?

Thanks
Deb

**Comment by joelmiller** [comment]
Yes.  There are ways to do this.  https://epidemicsonnetworks.readthedocs.io/en/latest/EoN.html has brief descriptions of the various functions.  Look at `fast_nonMarkov_SIR` and follow the link there it may help.  

The examples for chapter 9 may also help: https://epidemicsonnetworks.readthedocs.io/en/latest/Examples.html

**Comment by debmalya191** [comment]
@joelmiller  isnt this for a continous time?
