### ISSUE TITLE
Functional testing

### ISSUE THREAD

**Issue by hagberg** [springer-math/Mathematics-of-Epidemics-on-Networks#43]
Are there methods (preferably automated) to test the functionality of the code?
It would be good to be able to verify at minimum that the basic installation is functioning.
Related issue at https://github.com/openjournals/joss-reviews/issues/1731

**Comment by joelmiller** [comment]
I have merged the functional testing created by @tinghf .  I believe this will address this issue.

The tests are now under EoN/tests, and there is a readme file there created by @tinghf
