### ISSUE TITLE
Plot animation with a graph from matrix

### ISSUE THREAD

**Issue by atilaajones** [springer-math/Mathematics-of-Epidemics-on-Networks#52]
Hello. 
How can I use **save** and **animation** package with a simple graph created from adjacency matrix?  In the EoN page, there is a example with a graph Grid2D, but when I trie with a graph from adjacency matrix I received the error: _vertices' must be a 2d list or array with shape nx2_

Bellow I write part of my code:
```
A = np.matrix(np.matrix(pd.read_excel(os.path.abspath("teste")))) 
G = nx.from_numpy_matrix(A)
pos = {node:node for node in G}
sim_kwargs = {'pos': pos}
sim = EoN.fast_SIR(G, 2.0, 1.0, initial_infecteds = initial_infections,
               tmax = 40, return_full_data=True, sim_kwargs = sim_kwargs)

ani=sim.animate(ts_plots=['I', 'SIR'], node_size = 4)
ani.save('SIR_2dgrid.mp4', fps=5, extra_args=['-vcodec', 'libx264'])
```

**Comment by joelmiller** [comment]
Hello,

It's not clear to me where the error is occuring.  Can you tell me what line it's happening in?  Also it is likely to help if I know what version of numpy and matplotlib you have.

**Comment by atilaajones** [comment]
The error was the lack of installation of a package related to '-vcodec', 'libx264'. Thank you very much for your attention to my problem.

**Comment by joelmiller** [comment]
Great - glad to hear it's resolved.

Please come back if other issues arise.
