### ISSUE TITLE
General Design Qestion

### ISSUE THREAD

**Issue by TheAkashain** [springer-math/Mathematics-of-Epidemics-on-Networks#59]
I am currently looking into using EoN for research on disease modeling with more modern issues included (I'm between 2nd and 3rd year in university, for reference), and so I have a quick question.

Let's say I wanted to design a more custom model in EoN (let's say a complex model based on the general SEIR model for the sake simplicity) that included the following features:
- Asymptomatic and symptomatic cases
- Severe vs mild cases
- Hospitalizations 
- Quarantines (breaking all or some edges for a person)

Would it be possible to build this in EoN? If not, would it be possible to use EoN source code to design this? (I would happily submit it to the GitHub repository if desired after completion of my research) I would likely use a Erd ̋os–R ́enyi or Barabási–Albert network for early modeling.

**Comment by joelmiller** [comment]
This would be possible using the `Gillespie_simple_contagion` framework.  It's a little technical, but doable.  

For quarantine, I wouldn't actually break the edges, but rather adjust the transmission rate of those edges.  

https://epidemicsonnetworks.readthedocs.io/en/latest/Examples.html#non-sis-sir-processes-with-gillespie-simple-contagion

**Comment by TheAkashain** [comment]
@joelmiller Perfect! Thank you very much!
