### ISSUE TITLE
recovery_weight and compatibility with NetworkX 2.x

### ISSUE THREAD

**Issue by jaowen** [springer-math/Mathematics-of-Epidemics-on-Networks#66]
Hello,

In the function  `_get_rate_functions_`, I don't think the `recovery_weight` option is handled correctly if the user has a recent version of NetworkX. For compatibility, in line 124, `G.node` should be `G.nodes`.

**Comment by joelmiller** [comment]
The updated version on github (1.2rc1) should now fix this (the version installed by pip does not have this update)
