### ISSUE TITLE
confusing in the Competing Diseases example

### ISSUE THREAD

**Issue by mauimoana** [springer-math/Mathematics-of-Epidemics-on-Networks#74]
Hi - I am testing the Competing Diseases example in https://epidemicsonnetworks.readthedocs.io/en/latest/examples/Compete.html

A problem or bug I noticed  in the plot function as showed below
......
plt.plot(t, RS+IR+RR, '-.', label = 'Recovered from disease 1')
plt.plot(t, SR+RI+RR, '-.', label = 'Recovered from disease 2')

I think that the IR doesnt mean 'Recovered from disease 1'  but  'Recovered from disease 2',  and the RI doesnt mean 'Recovered from disease 2'  but  'Recovered from disease 1'.

I am not sure is it  true or not.

Thanks a lot.

**Comment by joelmiller** [comment]
You appear to be correct.  I'll try to get this fixed.

**Comment by wenchaohee** [comment]
OK, thanks a lot.
