### ISSUE TITLE
Erratum: SIS dynamics (Equation 3.5)

### ISSUE THREAD

**Issue by janmoelter** [springer-math/Mathematics-of-Epidemics-on-Networks#75]
It seems to me that the evolution equation for SS-pairs under SIS dynamics (Equation 3.5d) might be missing two terms. Specifically, since the number of SS-pairs increases from within the pair when SI-pairs recover, the terms _+γ<sub>i</sub> 〈I<sub>i</sub>S<sub>j</sub>〉_ and _+γ<sub>j</sub> 〈S<sub>i</sub>I<sub>j</sub>〉_ should appear in the corresponding evolution equation. This would then also make the equations consistent with the evolution equations after closures at the pair level have been introduced later in the book (Equation 3.26).

**Comment by joelmiller** [comment]
At first glance, it looks like you're right.  I'll need to look over it in more detail just to be sure. It looks like the SS pairs can only decrease in time, which of course isn't right.

**Comment by joelmiller** [comment]
Cleaning up the issues.  This was done, not yet closed.
