### ISSUE TITLE
how to get the node state by EoN?

### ISSUE THREAD

**Issue by King-1991** [springer-math/Mathematics-of-Epidemics-on-Networks#81]
Hi,
    Now I need to obtain the individuals' state at random steps. But I find the EoN only returns the  number of each state and their time. So how to do that? Thank you and looking forward to your reply.

**Comment by joelmiller** [comment]
By default that is what EoN returns.  But there is a flag `return_full_data` which is set to `False` by default.  If you set it to true, the return value changes.  You get a `simulation_investigation` object.  A description of some of the things you can do with that is here: https://epidemicsonnetworks.readthedocs.io/en/latest/EoN.html#simulation-investigation-toolkit

**Comment by joelmiller** [comment]
For example:

    sim = EoN.fast_SIR(G,1,2,return_full_data=True)
    sim.node_status(1,4.5)

will give you the status of node 1 at time 4.5.  However

    sim.node_history(1)

will give you the history of node 1 (times of transitions and what those new statuses are).  This is more interesting in SIS disease or more complicated processes.
