### ISSUE TITLE
Heterogeneous infectivity simulation

### ISSUE THREAD

**Issue by wenchaohee** [springer-math/Mathematics-of-Epidemics-on-Networks#82]
Hi Dr. Joel C Miller,

I was wondering is there any function of EoN for heterogeneous infectivity implementation?

Thank you for your time.

**Comment by joelmiller** [comment]
Yes it is possible to do this.  You have to do more work - you'll have to define .  This example has 2 subgroups and one group is more infectious than the other other.  https://epidemicsonnetworks.readthedocs.io/en/latest/examples/bipartite.html

If you can tell me a bit more about what you have in mind I may be able to help out more.

**Comment by wenchaohee** [comment]
Thank you for your reply. As some papers present, the distribution of number of secondary cases for Cov-19 is fat-tailed.  Thus, it seems better to implement this as heterogeneous infectivity, such as gamma-distributed infectivity. The module you mentioned above seems to simulate the diseases like HIV which men and women have different infectivity.
Thank you for your help.
Best wishes.
