### ISSUE TITLE
What transmission module means in SEIR model

### ISSUE THREAD

**Issue by wenchaohee** [springer-math/Mathematics-of-Epidemics-on-Networks#89]
Hi, could you help me explain what transmission module means in SEIR model?  The returned tuples (t,u,v)  means S>E, or E>R  ?

Thanks very much.

![image](https://user-images.githubusercontent.com/77086328/235436867-b3272ac4-a557-4d31-b3b1-dad28720b97f.png)

**Comment by joelmiller** [comment]
(t,u,v) means that at time t, u caused v to transition from S to E.

does that answer your question?

**Comment by wenchaohee** [comment]
Thanks very much for your help! It's exactly the answer what I want.  Another question: How could I get the status changing tuple of E to I ?

Thanks for your help again.
Best wishes.

**Comment by joelmiller** [comment]
For E to I there’s no involvement of any other node.  So there’s nothing like the transmissions.   However, the history of a node, including the E to I transition should be in `node_history`

**Comment by wenchaohee** [comment]
Got it. Thanks for your kindful help. So, is there any module that could return the status of Infected nodes in time series format?  
 Returns like (time1:A infected, time2:B infected..........)

**Comment by joelmiller** [comment]
Just to be clear, if you mean when did the individual acquire infection?  Then that is almost what is given in `transmissions`.  If you mean when did the individual become infectious, then I don't think you can directly get that, but it can be extracted from `node_history`.

**Comment by wenchaohee** [comment]
Got it. I mean the latter one. Thanks for your help. It's time for me to DIY. Haha!

Thanks for your time.
Best wishes!
