### ISSUE TITLE
Is the fast_SIR module belong to the complex or simple contagion ？

### ISSUE THREAD

**Issue by wenchaohee** [springer-math/Mathematics-of-Epidemics-on-Networks#91]
Hi, could you tell me whether the fast_SIR module belongs to the complex or simple contagions？

![image](https://github.com/springer-math/Mathematics-of-Epidemics-on-Networks/assets/77086328/be370ee4-cd92-45f7-beed-4a9697e918fd)

Thanks for your time.

**Comment by joelmiller** [comment]
It solves the SIR model, which is a type of 'simple contagion'.  It uses its own specialized method which is different from the 'simple contagion' code.

**Comment by wenchaohee** [comment]
Got it. Thanks for your kind help.
Best wishes.
